<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaiwanDrivingSchoolsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('taiwan_driving_schools')->delete();
        DB::table('taiwan_driving_schools')->insert([
            0 => 
            [
                'id' => 1,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '加昌駕訓班',
                'address' => '高雄市楠梓區學專路88號',
                'telephone' => '07-3655712',
                'fax' => '07-3624641',
                'is_recruiting_students' => 'Y',
            ],
            1 => 
            [
                'id' => 2,
                'office' => '臺北市區監理所',
                'station' => '金門監理站',
                'name' => '私立金門汽車駕駛訓練',
                'address' => '金門縣金寧鄉榜林村盤果西路8號',
                'telephone' => '082-329881',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            2 => 
            [
                'id' => 3,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '南陽駕訓班',
                'address' => '高雄市三民區民族一路311號',
                'telephone' => '07-3861187',
                'fax' => '07-3861184',
                'is_recruiting_students' => 'Y',
            ],
            3 => 
            [
                'id' => 4,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '和慷駕訓班',
                'address' => '高雄市小港區翠享南路76號',
                'telephone' => '07-8151970',
                'fax' => '07-8136725',
                'is_recruiting_students' => 'Y',
            ],
            4 => 
            [
                'id' => 5,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '新大益駕訓班',
                'address' => '高雄市楠梓區德民路1300號',
                'telephone' => '07-3643300',
                'fax' => '07-3653323',
                'is_recruiting_students' => 'Y',
            ],
            5 => 
            [
                'id' => 6,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '新永駕訓班',
                'address' => '高雄市苓雅區武營路485號',
                'telephone' => '07-7715522',
                'fax' => '07-7515945',
                'is_recruiting_students' => 'Y',
            ],
            6 => 
            [
                'id' => 7,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '大新駕訓班',
                'address' => '高雄市三民區河堤路50號',
                'telephone' => '07-3831009',
                'fax' => '07-3908355',
                'is_recruiting_students' => 'Y',
            ],
            7 => 
            [
                'id' => 8,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '長峰駕訓班',
                'address' => '高雄市楠梓區朝仁路300號',
                'telephone' => '07-3582005',
                'fax' => '07-3582866',
                'is_recruiting_students' => 'Y',
            ],
            8 => 
            [
                'id' => 9,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '大統駕訓班',
                'address' => '高雄市楠梓區加昌路602之11號',
                'telephone' => '07-3659462',
                'fax' => '07-3635120',
                'is_recruiting_students' => 'Y',
            ],
            9 => 
            [
                'id' => 10,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '雄工駕訓班',
                'address' => '高雄市三民區建工路419號',
                'telephone' => '07-3893066',
                'fax' => '07-3893066',
                'is_recruiting_students' => 'N',
            ],
            10 => 
            [
                'id' => 11,
                'office' => '臺北市區監理所',
                'station' => '金門監理站',
                'name' => '私立陽明汽車駕訓班',
                'address' => '金門縣金湖鎮陽明村',
                'telephone' => '082-351600',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            11 => 
            [
                'id' => 12,
                'office' => '高雄市區監理所',
                'station' => '高雄市區監理所',
                'name' => '南昌駕訓班',
                'address' => '高雄市小港區廠邊三路47號',
                'telephone' => '07-8034508',
                'fax' => '07-8067033',
                'is_recruiting_students' => 'Y',
            ],
            12 => 
            [
                'id' => 13,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '福安汽車駕訓班',
                'address' => '臺北市北投區大度路臨９號',
                'telephone' => '02-28936872',
                'fax' => '02-28950448',
                'is_recruiting_students' => 'Y',
            ],
            13 => 
            [
                'id' => 14,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '信泰汽車駕駛訓練班',
                'address' => '臺北市南港區重陽路２７７號',
                'telephone' => '02-27893000',
                'fax' => '02-26539374',
                'is_recruiting_students' => 'Y',
            ],
            14 => 
            [
                'id' => 15,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '文山汽車駕訓班',
                'address' => '臺北市文山區辛亥路四段１１６巷４７號',
                'telephone' => '02-29352222',
                'fax' => '02-86633888',
                'is_recruiting_students' => 'Y',
            ],
            15 => 
            [
                'id' => 16,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '現代汽車駕訓班',
                'address' => '臺北市北投區大度路三段１６３號',
                'telephone' => '02-28586006',
                'fax' => '02-28586060',
                'is_recruiting_students' => 'Y',
            ],
            16 => 
            [
                'id' => 17,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '大台北汽車駕訓班',
                'address' => '臺北市北投區大度路三段１８５號',
                'telephone' => '02-28585700',
                'fax' => '02-28582737',
                'is_recruiting_students' => 'Y',
            ],
            17 => 
            [
                'id' => 18,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '濱江汽車駕訓班',
                'address' => '臺北市中山區濱江街２１８號',
                'telephone' => '02-25077957',
                'fax' => '02-25011295',
                'is_recruiting_students' => 'Y',
            ],
            18 => 
            [
                'id' => 19,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '大湖汽車駕訓班',
                'address' => '臺北市內湖區康寧路一段156巷11號',
                'telephone' => '02-27955678',
                'fax' => '02-27955681',
                'is_recruiting_students' => 'Y',
            ],
            19 => 
            [
                'id' => 20,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '聯合汽車駕訓班',
                'address' => '臺北市北投區大度路一段３１號',
                'telephone' => '02-28936889',
                'fax' => '02-28931699',
                'is_recruiting_students' => 'N',
            ],
            20 => 
            [
                'id' => 21,
                'office' => '臺北市區監理所',
                'station' => '臺北市區監理所',
                'name' => '華南汽車駕訓班',
                'address' => '臺北市中山區濱江街２８６號',
                'telephone' => '02-25098188',
                'fax' => '02-25093868',
                'is_recruiting_students' => 'Y',
            ],
            21 => 
            [
                'id' => 22,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '明星汽車駕駛人訓練班',
                'address' => '新竹縣湖口鄉鳳山村鳳山崎８－３號',
                'telephone' => '03-5985353',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            22 => 
            [
                'id' => 23,
                'office' => '新竹區監理所',
                'station' => '苗栗監理站',
                'name' => '東昇汽車駕訓班',
                'address' => '苗栗縣頭屋鄉尖豐路１４１號',
                'telephone' => '037-250505',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            23 => 
            [
                'id' => 24,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '私立華興駕訓班',
                'address' => '桃園縣龍潭鄉民生路329號',
                'telephone' => '03-4700588',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            24 => 
            [
                'id' => 25,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '和昭駕訓班',
                'address' => '桃園縣蘆竹市五福村五福路２８號',
                'telephone' => '03-3529922',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            25 => 
            [
                'id' => 26,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '萬駿駕訓班',
                'address' => '桃園縣楊梅市萬大路３６號',
                'telephone' => '03-4825678',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            26 => 
            [
                'id' => 27,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '大興駕訓班',
                'address' => '桃園縣大園鄉永興路１４２號',
                'telephone' => '03-3864222',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            27 => 
            [
                'id' => 28,
                'office' => '新竹區監理所',
                'station' => '新竹市監理站',
                'name' => '新竹客運駕駛訓練班',
                'address' => '新竹市明湖路四八四號',
                'telephone' => '03-5201127',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            28 => 
            [
                'id' => 29,
                'office' => '新竹區監理所',
                'station' => '苗栗監理站',
                'name' => '正中汽車駕駛人訓練班',
                'address' => '苗栗縣苗栗市文山里文山７２－２號',
                'telephone' => '037-356703',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            29 => 
            [
                'id' => 30,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '華亞隆勝駕駛訓練班有',
                'address' => '桃園縣龜山鄉華亞一路６巷１６號',
                'telephone' => '03-3280111',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            30 => 
            [
                'id' => 31,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '聯合駕訓班',
                'address' => '桃園縣桃園市文中路３３７巷２號',
                'telephone' => '03-3606611',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            31 => 
            [
                'id' => 32,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '龍興駕訓班',
                'address' => '桃園縣龍潭鄉中興路４６６巷３８號',
                'telephone' => '03-4790011',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            32 => 
            [
                'id' => 33,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '大明駕訓班',
                'address' => '桃園縣楊梅市中山北路２段１號',
                'telephone' => '03-4826991',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            33 => 
            [
                'id' => 34,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '大?駕訓班',
                'address' => '桃園縣楊梅市上田里和平路365號',
                'telephone' => '03-4781445',
                'fax' => '34781447',
                'is_recruiting_students' => 'Y',
            ],
            34 => 
            [
                'id' => 35,
                'office' => '新竹區監理所',
                'station' => '新竹市監理站',
                'name' => '新芳鄰駕駛人訓練班',
                'address' => '新竹市埔頂里２鄰埔頂路９９巷１０弄２２號',
                'telephone' => '03-5752222',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            35 => 
            [
                'id' => 36,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '大同汽車駕駛人訓練班',
                'address' => '新竹縣竹東鎮中興路一段１４７巷１３１號',
                'telephone' => '03-5821531',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            36 => 
            [
                'id' => 37,
                'office' => '新竹區監理所',
                'station' => '苗栗監理站',
                'name' => '榮利汽車駕訓班',
                'address' => '苗栗縣通霄鎮五北里４鄰３３－２號',
                'telephone' => '037-750767',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            37 => 
            [
                'id' => 38,
                'office' => '新竹區監理所',
                'station' => '苗栗監理站',
                'name' => '光明汽車駕訓班',
                'address' => '苗栗縣竹南鎮佳興里１鄰照南８４號',
                'telephone' => '037-629068',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            38 => 
            [
                'id' => 39,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '大展駕訓班',
                'address' => '桃園縣桃園市龍泉五街１２０號',
                'telephone' => '03-3699992',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            39 => 
            [
                'id' => 40,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '大通駕訓班',
                'address' => '桃園縣平鎮市宋屋里６鄰廣興１７０號',
                'telephone' => '03-4928835',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            40 => 
            [
                'id' => 41,
                'office' => '新竹區監理所',
                'station' => '新竹市監理站',
                'name' => '宏城汽車駕駛訓練班',
                'address' => '新竹市中華路一段二巷二二號',
                'telephone' => '03-5322121',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            41 => 
            [
                'id' => 42,
                'office' => '新竹區監理所',
                'station' => '新竹市監理站',
                'name' => '東亞汽車駕訓班',
                'address' => '新竹市中華路一段１２１號',
                'telephone' => '03-5328997',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            42 => 
            [
                'id' => 43,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '日新汽車駕駛人訓練班',
                'address' => '新竹縣竹北市鳳岡路二段５４０巷１３６號',
                'telephone' => '03-5561212',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            43 => 
            [
                'id' => 44,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '私立大觀駕訓班',
                'address' => '桃園縣觀音鄉坑尾村１５鄰１０７號－１',
                'telephone' => '03-4734600',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            44 => 
            [
                'id' => 45,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '懷德駕訓班',
                'address' => '桃園縣桃園市三元街４６８號',
                'telephone' => '03-3330270',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            45 => 
            [
                'id' => 46,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '長榮駕訓班',
                'address' => '桃園縣桃園市經國路３９０號',
                'telephone' => '03-3578330',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            46 => 
            [
                'id' => 47,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '國泰駕訓班',
                'address' => '桃園縣桃園市國際路２段７０號',
                'telephone' => '03-3601155',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            47 => 
            [
                'id' => 48,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '立青駕訓班',
                'address' => '桃園縣中壢市內壢大華路４５０號',
                'telephone' => '03-4555301',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            48 => 
            [
                'id' => 49,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '永勝汽車駕駛人訓練班',
                'address' => '新竹縣湖口鄉新竹縣湖口鄉信昌街60號',
                'telephone' => '03-5906837',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            49 => 
            [
                'id' => 50,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '亞東汽車駕駛人訓練班',
                'address' => '新竹縣新埔鎮文山里土地公埔３鄰關埔路水車頭段８１９巷１０３號',
                'telephone' => '03-5881962',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            50 => 
            [
                'id' => 51,
                'office' => '新竹區監理所',
                'station' => '苗栗監理站',
                'name' => '永昇汽車駕訓班',
                'address' => '苗栗縣頭份鎮顯會路４９號',
                'telephone' => '037-691590',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            51 => 
            [
                'id' => 52,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '育青駕訓班',
                'address' => '桃園縣桃園市陽明五街２號２Ｆ',
                'telephone' => '03-3612908',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            52 => 
            [
                'id' => 53,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '大同駕訓班',
                'address' => '桃園縣桃園市泰昌三街５１號',
                'telephone' => '03-3709922',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            53 => 
            [
                'id' => 54,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '太子駕訓班',
                'address' => '桃園縣中壢市後寮二路３３９號',
                'telephone' => '03-4361488',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            54 => 
            [
                'id' => 55,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '忠原駕訓班',
                'address' => '桃園縣中壢市中華路１６７號',
                'telephone' => '03-4523711',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            55 => 
            [
                'id' => 56,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '長庚駕訓班',
                'address' => '桃園縣龜山鄉文化三路５４５號',
                'telephone' => '03-3270730',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            56 => 
            [
                'id' => 57,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '中興汽車駕駛人訓練班',
                'address' => '新竹縣湖口鄉鳳山村２鄰１號',
                'telephone' => '03-5984225',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            57 => 
            [
                'id' => 58,
                'office' => '新竹區監理所',
                'station' => '新竹區監理所',
                'name' => '新竹安全駕駛訓練班股份有限公司',
                'address' => '新竹縣新豐鄉新竹縣新豐鄉重興村榮華街１６８號',
                'telephone' => '03-5592637',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            58 => 
            [
                'id' => 59,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '鴻興駕訓班',
                'address' => '桃園縣中壢市龍岡路３段１１５巷６５弄１２號',
                'telephone' => '03-4573031',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            59 => 
            [
                'id' => 60,
                'office' => '新竹區監理所',
                'station' => '中壢監理站',
                'name' => '宏國駕訓班',
                'address' => '桃園縣中壢市龍東路２５５巷５６弄６７號',
                'telephone' => '03-4655588',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            60 => 
            [
                'id' => 61,
                'office' => '新竹區監理所',
                'station' => '新竹市監理站',
                'name' => '華江駕訓班',
                'address' => '新竹市成功路１９１號',
                'telephone' => '03-5234447',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            61 => 
            [
                'id' => 62,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '花旗駕駛訓練班有限公',
                'address' => '桃園縣八德市桃德路250號',
                'telephone' => '03-3613645',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            62 => 
            [
                'id' => 63,
                'office' => '新竹區監理所',
                'station' => '桃園監理站',
                'name' => '大新駕訓班',
                'address' => '桃園縣八德市東勇北街７６號',
                'telephone' => '03-3751188',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            63 => 
            [
                'id' => 64,
                'office' => '臺北區監理所',
                'station' => '基隆監理站',
                'name' => '國聯汽車駕訓班',
                'address' => '基隆市安樂區樂利三街３０巷８０號',
                'telephone' => '24318111',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            64 => 
            [
                'id' => 65,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '淡欣',
                'address' => '新北市淡水區中正路２段３１號',
                'telephone' => '28057772',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            65 => 
            [
                'id' => 66,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '亞洲汽車駕駛人訓練班',
                'address' => '宜蘭縣冬山鄉照安路２６９－１號',
                'telephone' => '03-9591166',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            66 => 
            [
                'id' => 67,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '正愛汽車駕駛人訓練班',
                'address' => '宜蘭縣冬山鄉大進路１５３號',
                'telephone' => '03-9512567',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            67 => 
            [
                'id' => 68,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大世紀',
                'address' => '新北市板橋區府中路２２號２樓',
                'telephone' => '2251-2222',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            68 => 
            [
                'id' => 69,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大龍德',
                'address' => '新北市鶯歌區中正三路鄭厝巷１４號之３',
                'telephone' => '26704023',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            69 => 
            [
                'id' => 70,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大順',
                'address' => '新北市淡水區中山北路一段２０７巷７８號',
                'telephone' => '2623-0632',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            70 => 
            [
                'id' => 71,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '名成',
                'address' => '新北市泰山區泰林路一段１５號',
                'telephone' => '85313399',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            71 => 
            [
                'id' => 72,
                'office' => '臺北區監理所',
                'station' => '基隆監理站',
                'name' => '新成功駕訓班',
                'address' => '新北市汐止區大同路３段５７９號',
                'telephone' => '86485858',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            72 => 
            [
                'id' => 73,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大新店駕訓班有限公司',
                'address' => '新北市新店區安和路2段179號',
                'telephone' => '22118380',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            73 => 
            [
                'id' => 74,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '名人',
                'address' => '花蓮縣吉安鄉東昌村名人１號',
                'telephone' => '03-8523220',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            74 => 
            [
                'id' => 75,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '第一',
                'address' => '新北市三重區成功路７８號',
                'telephone' => '29772374',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            75 => 
            [
                'id' => 76,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '新北市私立板新汽車駕駛人機車訓練分班',
                'address' => '新北市板橋區新北市信義路２７９巷２７號',
                'telephone' => '02-29591131',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            76 => 
            [
                'id' => 77,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '公路人員訓練所',
                'address' => '新北市中和區中山路３段７９號',
                'telephone' => '82212888',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            77 => 
            [
                'id' => 78,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '龍一',
                'address' => '新北市板橋區文化路２段５０５巷３號４樓５樓',
                'telephone' => '22519595',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            78 => 
            [
                'id' => 79,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '美侖',
                'address' => '花蓮縣吉安鄉仁和村中正路二段８１號',
                'telephone' => '03-8526973',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            79 => 
            [
                'id' => 80,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '成泰',
                'address' => '新北市泰山區泰林路1段1巷16-8號',
                'telephone' => '22968355',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            80 => 
            [
                'id' => 81,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '板新',
                'address' => '新北市板橋區信義路二七九巷十三之一號',
                'telephone' => '29687779',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            81 => 
            [
                'id' => 82,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '輔大駕訓班機車分班',
                'address' => '新北市泰山區明志路二段322號2樓',
                'telephone' => '285124168',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            82 => 
            [
                'id' => 83,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '螢橋',
                'address' => '花蓮縣吉安鄉海濱路１４８號',
                'telephone' => '03-8421456',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            83 => 
            [
                'id' => 84,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '幸福汽車駕駛人訓練班',
                'address' => '宜蘭縣宜蘭市鎮平路７巷２１號',
                'telephone' => '03-9281128',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            84 => 
            [
                'id' => 85,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大同',
                'address' => '新北市樹林區保安街１段３３１號之１',
                'telephone' => '26758438',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            85 => 
            [
                'id' => 86,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '通運',
                'address' => '新北市五股區工商路１３８號',
                'telephone' => '22923001',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            86 => 
            [
                'id' => 87,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '佑名',
                'address' => '新北市新店區寶元路2段1巷1-2號',
                'telephone' => '86650876',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            87 => 
            [
                'id' => 88,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '日月駕訓班',
                'address' => '新北市蘆洲區永安南路一段1巷1弄22號',
                'telephone' => '29890999',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            88 => 
            [
                'id' => 89,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '統一',
                'address' => '花蓮縣吉安鄉東昌村名人９８號',
                'telephone' => '03-8523656',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            89 => 
            [
                'id' => 90,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '龍德汽車駕駛人訓練班',
                'address' => '宜蘭縣三星鄉清洲路１３－３號',
                'telephone' => '03-9560368',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            90 => 
            [
                'id' => 91,
                'office' => '臺北區監理所',
                'station' => '基隆監理站',
                'name' => '大龍港汽車駕訓班',
                'address' => '新北市汐止區忠一街９巷１２號',
                'telephone' => '26433007',
                'fax' => '02-2643300',
                'is_recruiting_students' => 'Y',
            ],
            91 => 
            [
                'id' => 92,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '三榮',
                'address' => '新北市三峽區介壽路２段１６９巷２號１樓',
                'telephone' => '86763386',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            92 => 
            [
                'id' => 93,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '海山',
                'address' => '新北市土城區廣興街３８號',
                'telephone' => '89663311',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            93 => 
            [
                'id' => 94,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '統一',
                'address' => '新北市泰山區泰林路一段十七號',
                'telephone' => '85311188',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            94 => 
            [
                'id' => 95,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '良友汽車駕駛人訓練班',
                'address' => '宜蘭縣冬山鄉照安路２６９號',
                'telephone' => '03-9591167',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            95 => 
            [
                'id' => 96,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大中華',
                'address' => '新北市板橋區大觀路２段２６５巷７－８號',
                'telephone' => '22754325',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            96 => 
            [
                'id' => 97,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '國泰汽車駕駛人訓練班',
                'address' => '宜蘭縣員山鄉新城路１８１－５號',
                'telephone' => '03-9222778',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            97 => 
            [
                'id' => 98,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '飛龍',
                'address' => '新北市樹林區工興街５號',
                'telephone' => '86881111',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            98 => 
            [
                'id' => 99,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '北聯',
                'address' => '新北市鶯歌區西湖街５３巷１８號',
                'telephone' => '26784488',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            99 => 
            [
                'id' => 100,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '太順',
                'address' => '新北市樹林區八德街１１９號',
                'telephone' => '86869266',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            100 => 
            [
                'id' => 101,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '九龍',
                'address' => '新北市板橋區永豐街１號２樓',
                'telephone' => '22557769',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            101 => 
            [
                'id' => 102,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '輔大',
                'address' => '新北市泰山區貴鳳街１號２樓',
                'telephone' => '29012369',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            102 => 
            [
                'id' => 103,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '徐匯汽車駕駛人訓練班',
                'address' => '新北市三重區永福街256及258號2樓',
                'telephone' => '29994860',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            103 => 
            [
                'id' => 104,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '莊敬',
                'address' => '新北市新店區民生路１４號',
                'telephone' => '22186784',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            104 => 
            [
                'id' => 105,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '日友',
                'address' => '花蓮縣鳳林鎮長橋里長二路１２１號',
                'telephone' => '03-8751518',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            105 => 
            [
                'id' => 106,
                'office' => '臺北區監理所',
                'station' => '基隆監理站',
                'name' => '培德高職附設駕訓班',
                'address' => '基隆市信義區培德路７３號',
                'telephone' => '24653781',
                'fax' => '24653781',
                'is_recruiting_students' => 'Y',
            ],
            106 => 
            [
                'id' => 107,
                'office' => '臺北區監理所',
                'station' => '宜蘭監理站',
                'name' => '宜林汽車駕駛人訓練',
                'address' => '宜蘭縣宜蘭市中山路５段１４６號',
                'telephone' => '03-9288000',
                'fax' => '',
                'is_recruiting_students' => 'Y',
            ],
            107 => 
            [
                'id' => 108,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大慈',
                'address' => '新北市三峽區大智路２號',
                'telephone' => '2672-8100',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            108 => 
            [
                'id' => 109,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大?',
                'address' => '新北市中和區永和路３５６巷６７號',
                'telephone' => '22225188',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            109 => 
            [
                'id' => 110,
                'office' => '臺北區監理所',
                'station' => '臺北區監理所',
                'name' => '大明',
                'address' => '新北市蘆洲區三民路１４８號１、２樓',
                'telephone' => '22911999',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            110 => 
            [
                'id' => 111,
                'office' => '臺北區監理所',
                'station' => '花蓮監理站',
                'name' => '玉里駕訓班',
                'address' => '花蓮縣玉里鎮大禹里酸柑９之１號',
                'telephone' => '03-8889789',
                'fax' => '',
                'is_recruiting_students' => 'N',
            ],
            111 => 
            [
                'id' => 112,
                'office' => '臺中區監理所',
                'station' => '臺中區監理所',
                'name' => '花旗',
                'address' => '臺中市北屯區松茂里九甲巷１１－５號',
                'telephone' => '04-22441417',
                'fax' => '04-22436032',
                'is_recruiting_students' => 'Y',
            ],
            112 => 
            [
                'id' => 113,
                'office' => '臺中區監理所',
                'station' => '臺中區監理所',
                'name' => '世全',
                'address' => '臺中市西屯區福星路６６９號',
                'telephone' => '04-27017111',
                'fax' => '04-27017147',
                'is_recruiting_students' => 'Y',
            ],
            113 => 
            [
                'id' => 114,
                'office' => '臺中區監理所',
                'station' => '臺中區監理所',
                'name' => '三華',
                'address' => '臺中市沙鹿區永寧路３６２號',
                'telephone' => '04-26656925',
                'fax' => '04-26655396',
                'is_recruiting_students' => 'Y',
            ],
            114 => 
            [
                'id' => 115,
                'office' => '臺中區監理所',
                'station' => '彰化監理站',
                'name' => '國彰汽車駕駛人訓練班',
                'address' => '彰化縣花壇鄉北口村中山路２段５８１號',
                'telephone' => '04-7863265',
                'fax' => '04-7878629',
                'is_recruiting_students' => 'Y',
            ],
            115 => 
            [
                'id' => 116,
                'office' => '臺中區監理所',
                'station' => '豐原監理站',
                'name' => '大豐汽車駕駛人訓練班',
                'address' => '臺中市霧峰區草湖路１８５號(法規教室容納７８人汽構教室容納７８人）',
                    'telephone' => '04-23392399',
                    'fax' => '04-23394294',
                    'is_recruiting_students' => 'Y',
                ],
                116 => 
                [
                    'id' => 117,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立新生鴐訓班',
                    'address' => '南投縣埔里鎮西安路一段５５５巷１０號',
                    'telephone' => '049-2987878',
                    'fax' => '049-2984849',
                    'is_recruiting_students' => 'Y',
                ],
                117 => 
                [
                    'id' => 118,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '逢甲',
                    'address' => '臺中市西屯區西屯路同志巷１０－２５號',
                    'telephone' => '04-27003166',
                    'fax' => '04-27084005',
                    'is_recruiting_students' => 'Y',
                ],
                118 => 
                [
                    'id' => 119,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立大益駕訓班',
                    'address' => '南投縣竹山鎮桂林里中正巷１３－３號',
                    'telephone' => '049-2659568',
                    'fax' => '049-2659569',
                    'is_recruiting_students' => 'Y',
                ],
                119 => 
                [
                    'id' => 120,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '自立汽車駕駛人訓練班',
                    'address' => '彰化縣員林鎮三義里惠明街320號',
                    'telephone' => '04-8351322',
                    'fax' => '',
                    'is_recruiting_students' => 'Y',
                ],
                120 => 
                [
                    'id' => 121,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '華江',
                    'address' => '臺中市西屯區后庄七街259號',
                    'telephone' => '04-24263577',
                    'fax' => '04-24256353',
                    'is_recruiting_students' => 'Y',
                ],
                121 => 
                [
                    'id' => 122,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '華豐汽車駕駛人練班',
                    'address' => '臺中市大甲區甲后路５３－４２號',
                    'telephone' => '04-26861686',
                    'fax' => '04-26861668',
                    'is_recruiting_students' => 'Y',
                ],
                122 => 
                [
                    'id' => 123,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立成功駕訓班',
                    'address' => '南投縣草屯鎮成功路１段９２５巷２號',
                    'telephone' => '049-2311497',
                    'fax' => '049-2314967',
                    'is_recruiting_students' => 'Y',
                ],
                123 => 
                [
                    'id' => 124,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '豐田汽車駕駛人訓練班',
                    'address' => '彰化縣員林鎮中東里山?路５段３１２巷１６０號',
                    'telephone' => '04-8362187',
                    'fax' => '04-8362345',
                    'is_recruiting_students' => 'Y',
                ],
                124 => 
                [
                    'id' => 125,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '育大汽車駕駛人訓練班',
                    'address' => '彰化縣溪湖鎮二溪路1段419之1號',
                    'telephone' => '04-8856125',
                    'fax' => '04-8854850',
                    'is_recruiting_students' => 'Y',
                ],
                125 => 
                [
                    'id' => 126,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立育英駕訓班',
                    'address' => '南投縣埔里鎮清新里育英街３００號',
                    'telephone' => '049-2985995',
                    'fax' => '049-2987581',
                    'is_recruiting_students' => 'Y',
                ],
                126 => 
                [
                    'id' => 127,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立水里駕訓班',
                    'address' => '南投縣水里鄉玉峰村仁愛路８－１號',
                    'telephone' => '049-2778166',
                    'fax' => '049-2778167',
                    'is_recruiting_students' => 'Y',
                ],
                127 => 
                [
                    'id' => 128,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '福海汽車駕駛人訓練班',
                    'address' => '彰化縣芳苑鄉王功村海埔路1880號',
                    'telephone' => '04-8934557',
                    'fax' => '',
                    'is_recruiting_students' => 'N',
                ],
                128 => 
                [
                    'id' => 129,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '北斗汽車駕駛人訓練班',
                    'address' => '彰化縣埤頭鄉斗苑東路１－１８號',
                    'telephone' => '04-8885678',
                    'fax' => '04-8888933',
                    'is_recruiting_students' => 'Y',
                ],
                129 => 
                [
                    'id' => 130,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '樹德',
                    'address' => '臺中市太平區樹德八街３５號',
                    'telephone' => '04-23950909',
                    'fax' => '04-23957025',
                    'is_recruiting_students' => 'Y',
                ],
                130 => 
                [
                    'id' => 131,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '高速',
                    'address' => '臺中市西屯區西屯路3段81-1號',
                    'telephone' => '04-24519226',
                    'fax' => '04-24519227',
                    'is_recruiting_students' => 'Y',
                ],
                131 => 
                [
                    'id' => 132,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '東海',
                    'address' => '臺中市大肚區遊園路１段１２６號',
                    'telephone' => '04-26911732',
                    'fax' => '04-26911735',
                    'is_recruiting_students' => 'Y',
                ],
                132 => 
                [
                    'id' => 133,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '中山',
                    'address' => '臺中市南區建國北路１段２２６號',
                    'telephone' => '04-24723000',
                    'fax' => '04-24726252',
                    'is_recruiting_students' => 'Y',
                ],
                133 => 
                [
                    'id' => 134,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '瑞聯',
                    'address' => '臺中市西屯區西屯路三段１６２－９０號',
                    'telephone' => '04-24613496',
                    'fax' => '04-24617802',
                    'is_recruiting_students' => 'Y',
                ],
                134 => 
                [
                    'id' => 135,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '全國汽車駕駛人訓練班',
                    'address' => '彰化縣鹿港鎮海埔里顏厝巷６７－２３號',
                    'telephone' => '04-7789222',
                    'fax' => '04-7743350',
                    'is_recruiting_students' => 'Y',
                ],
                135 => 
                [
                    'id' => 136,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '文山汽車駕駛人訓練班',
                    'address' => '彰化縣二林鎮後厝里長春路４８３號',
                    'telephone' => '04-8965882',
                    'fax' => '',
                    'is_recruiting_students' => 'Y',
                ],
                136 => 
                [
                    'id' => 137,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '民光汽車駕駛人訓練班',
                    'address' => '彰化縣和美鎮彰新路2段243巷110號',
                    'telephone' => '04-7355195',
                    'fax' => '04-7355484',
                    'is_recruiting_students' => 'Y',
                ],
                137 => 
                [
                    'id' => 138,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立大?駕訓班',
                    'address' => '南投縣南投市軍功里東山路４８１號',
                    'telephone' => '049-2224663',
                    'fax' => '049-2233266',
                    'is_recruiting_students' => 'Y',
                ],
                138 => 
                [
                    'id' => 139,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立大榮駕訓班',
                    'address' => '南投縣南投市三興里嶺興路６６號',
                    'telephone' => '049-2229626',
                    'fax' => '049-2224001',
                    'is_recruiting_students' => 'Y',
                ],
                139 => 
                [
                    'id' => 140,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '培英汽車駕駛人訓練班',
                    'address' => '彰化縣彰化市國聖里國聖路３３５巷１０之２號',
                    'telephone' => '04-7388727',
                    'fax' => '04-7388757',
                    'is_recruiting_students' => 'Y',
                ],
                140 => 
                [
                    'id' => 141,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '連豐汽車駕駛人訓練班',
                    'address' => '臺中市神岡區五權路88巷17號（小型車：7324平方公尺:大客貨:8000平方公尺',
                    'telephone' => '04-25279797',
                    'fax' => '04-25295780',
                    'is_recruiting_students' => 'Y',
                ],
                141 => 
                [
                    'id' => 142,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立益新鴐訓班',
                    'address' => '南投縣草屯鎮新豐里中正路１６１７號',
                    'telephone' => '049-2334535',
                    'fax' => '049-2365026',
                    'is_recruiting_students' => 'Y',
                ],
                142 => 
                [
                    'id' => 143,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '甲工汽車駕駛人訓練班',
                    'address' => '臺中市外埔區開元路６６－６號',
                    'telephone' => '04-26881699',
                    'fax' => '04-26881189',
                    'is_recruiting_students' => 'Y',
                ],
                143 => 
                [
                    'id' => 144,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '私立德山駕訓班',
                    'address' => '南投縣竹山鎮延平里東鄉路８－１２６號',
                    'telephone' => '049-2641439',
                    'fax' => '049-2642439',
                    'is_recruiting_students' => 'Y',
                ],
                144 => 
                [
                    'id' => 145,
                    'office' => '臺中區監理所',
                    'station' => '南投監理站',
                    'name' => '公路局公路人員訓練',
                    'address' => '南投縣南投市光明一路３００號',
                    'telephone' => '049-2339171',
                    'fax' => '',
                    'is_recruiting_students' => 'Y',
                ],
                145 => 
                [
                    'id' => 146,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '富國駕訓班',
                    'address' => '臺中市外埔區水美里山美路519號',
                    'telephone' => '04-26805226',
                    'fax' => '04-26862676',
                    'is_recruiting_students' => 'Y',
                ],
                146 => 
                [
                    'id' => 147,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '修平',
                    'address' => '臺中市大里區仁化路３００號',
                    'telephone' => '04-24925259',
                    'fax' => '04-24913752',
                    'is_recruiting_students' => 'Y',
                ],
                147 => 
                [
                    'id' => 148,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '西苑',
                    'address' => '臺中市南屯區春社里嶺東路１２０號',
                    'telephone' => '04-23811832',
                    'fax' => '04-23811831',
                    'is_recruiting_students' => 'Y',
                ],
                148 => 
                [
                    'id' => 149,
                    'office' => '臺中區監理所',
                    'station' => '臺中區監理所',
                    'name' => '中港',
                    'address' => '臺中市沙鹿區中棲路１６８號（大車８０１５，小車６１０８·２）',
                    'telephone' => '04-26314176',
                    'fax' => '04-26313329',
                    'is_recruiting_students' => 'Y',
                ],
                149 => 
                [
                    'id' => 150,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '揚勳汽車駕駛人訓練班',
                    'address' => '彰化縣鹿港鎮永靖路１３９號',
                    'telephone' => '04-7762960',
                    'fax' => '04-7771233',
                    'is_recruiting_students' => 'Y',
                ],
                150 => 
                [
                    'id' => 151,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '花旗汽車駕駛人訓練班',
                    'address' => '臺中市太平區華安街７５號',
                    'telephone' => '04-22713555',
                    'fax' => '04-22712545',
                    'is_recruiting_students' => 'Y',
                ],
                151 => 
                [
                    'id' => 152,
                    'office' => '臺中區監理所',
                    'station' => '彰化監理站',
                    'name' => '國華汽車駕駛人訓練班',
                    'address' => '彰化縣和美鎮竹營里忠孝路６６號',
                    'telephone' => '04-7562445',
                    'fax' => '04-7573830',
                    'is_recruiting_students' => 'Y',
                ],
                152 => 
                [
                    'id' => 153,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '豐年汽車駕駛人訓練班',
                'address' => '臺中市大里區大智路600號(法規教室容納47人汽構教室容納37人)',
                    'telephone' => '04-22806677',
                    'fax' => '04-22809714',
                    'is_recruiting_students' => 'Y',
                ],
                153 => 
                [
                    'id' => 154,
                    'office' => '臺中區監理所',
                    'station' => '豐原監理站',
                    'name' => '大統汽車駕駛人訓練班',
                'address' => '臺中市太平區光德路419號（法規教室容納50人，汽構教室49人)',
                'telephone' => '04-23515678',
                'fax' => '04-23515655',
                'is_recruiting_students' => 'Y',
            ],
            154 => 
            [
                'id' => 155,
                'office' => '臺中區監理所',
                'station' => '豐原監理站',
                'name' => '大千汽車駕駛人訓練班',
            'address' => '臺中市大雅區雅環路１段５７號（學科教室容納學員40人，術科教室40人)',
            'telephone' => '04-25673313',
            'fax' => '04-25673313',
            'is_recruiting_students' => 'Y',
        ],
        155 => 
        [
            'id' => 156,
            'office' => '臺中區監理所',
            'station' => '南投監理站',
            'name' => '私立新天地駕訓班',
            'address' => '南投縣草屯鎮成功路一段９２５巷９號',
            'telephone' => '049-2322389',
            'fax' => '049-2302817',
            'is_recruiting_students' => 'Y',
        ],
        156 => 
        [
            'id' => 157,
            'office' => '臺中區監理所',
            'station' => '臺中區監理所',
            'name' => '元泰',
            'address' => '臺中市南區復興北路588號',
            'telephone' => '04-22630563',
            'fax' => '04-22626491',
            'is_recruiting_students' => 'Y',
        ],
        157 => 
        [
            'id' => 158,
            'office' => '臺中區監理所',
            'station' => '臺中區監理所',
            'name' => '中台',
            'address' => '臺中市北屯區雙十路一段十九巷二十號　小車７０５０　大車８０００',
            'telephone' => '04-24362933',
            'fax' => '04-24364420',
            'is_recruiting_students' => 'Y',
        ],
        158 => 
        [
            'id' => 159,
            'office' => '臺中區監理所',
            'station' => '臺中區監理所',
            'name' => '世華',
            'address' => '臺中市北屯區太原路三段７００號',
            'telephone' => '04-24362318',
            'fax' => '04-24365183',
            'is_recruiting_students' => 'Y',
        ],
        159 => 
        [
            'id' => 160,
            'office' => '臺中區監理所',
            'station' => '彰化監理站',
            'name' => '中興汽車駕駛人訓練班',
            'address' => '彰化縣埤頭鄉元埔村文化路１４５號',
            'telephone' => '04-8780108',
            'fax' => '04-8780072',
            'is_recruiting_students' => 'Y',
        ],
        160 => 
        [
            'id' => 161,
            'office' => '臺中區監理所',
            'station' => '豐原監理站',
            'name' => '新豐田駕訓班',
            'address' => '臺中市豐原區豐原市東興街８５號（法規教室容納學員40人，汽構教室40人）',
            'telephone' => '04-25243113',
            'fax' => '04-25206983',
            'is_recruiting_students' => 'Y',
        ],
        161 => 
        [
            'id' => 162,
            'office' => '臺中區監理所',
            'station' => '彰化監理站',
            'name' => '國光汽車駕駛人訓練班',
            'address' => '彰化縣溪州鄉中山路２段６４６號',
            'telephone' => '04-8893353',
            'fax' => '04-8891353',
            'is_recruiting_students' => 'Y',
        ],
        162 => 
        [
            'id' => 163,
            'office' => '臺中區監理所',
            'station' => '豐原監理站',
            'name' => '利坤達駕訓班',
            'address' => '臺中市豐原區鐮村路465巷106號',
            'telephone' => '04-25366796',
            'fax' => '04-25393808',
            'is_recruiting_students' => 'Y',
        ],
        163 => 
        [
            'id' => 164,
            'office' => '臺中區監理所',
            'station' => '豐原監理站',
            'name' => '中山汽車駕駛人訓練班',
            'address' => '臺中市豐原區三豐路1010號（法規教室容納學53人，汽構教室容納學員30人）',
            'telephone' => '04-25296277',
            'fax' => '04-25244585',
            'is_recruiting_students' => 'Y',
        ],
        164 => 
        [
            'id' => 165,
            'office' => '臺中區監理所',
            'station' => '彰化監理站',
            'name' => '社頭汽車駕駛人訓練班',
            'address' => '彰化縣社頭鄉員集路２段２４７巷１０５號',
            'telephone' => '04-8731377',
            'fax' => '04-8739336',
            'is_recruiting_students' => 'Y',
        ],
        165 => 
        [
            'id' => 166,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '巨人高中附設駕訓班',
            'address' => '雲林縣北港鎮大同路６４７號',
            'telephone' => '05-7834768',
            'fax' => '05-7810995',
            'is_recruiting_students' => 'Y',
        ],
        166 => 
        [
            'id' => 167,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '麗園駕訓班',
            'address' => '嘉義市東區林森東路８４６號',
            'telephone' => '05-2771001',
            'fax' => '05-2768357',
            'is_recruiting_students' => 'Y',
        ],
        167 => 
        [
            'id' => 168,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '進發駕訓班',
            'address' => '臺南市安南區北安路三段４０２號',
            'telephone' => '06-2559866',
            'fax' => '981860058',
            'is_recruiting_students' => 'N',
        ],
        168 => 
        [
            'id' => 169,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '日上駕訓班',
            'address' => '臺南市永康區復華三街９５號',
            'telephone' => '06-2355701',
            'fax' => '06-3110554',
            'is_recruiting_students' => 'Y',
        ],
        169 => 
        [
            'id' => 170,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '明和駕訓班',
            'address' => '雲林縣斗六市斗六市西平路１０００號',
            'telephone' => '05-5518383',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        170 => 
        [
            'id' => 171,
            'office' => '嘉義區監理所',
            'station' => '麻豆監理站',
            'name' => '來來駕訓班',
            'address' => '臺南市善化區溪美里溪尾２１７號之２（楊胡雪等４人合夥）',
            'telephone' => '06-5818991',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        171 => 
        [
            'id' => 172,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '永慶駕訓班',
            'address' => '雲林縣古坑鄉水碓村１８５之２０號',
            'telephone' => '05-5353855',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        172 => 
        [
            'id' => 173,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '中正駕訓班',
            'address' => '嘉義縣民雄鄉三興村文學路６號',
            'telephone' => '05-2722111',
            'fax' => '05-2721309',
            'is_recruiting_students' => 'Y',
        ],
        173 => 
        [
            'id' => 174,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '美的駕訓班',
            'address' => '嘉義市東區吳鳳南路２７２號',
            'telephone' => '05-2234567',
            'fax' => '05-2234935',
            'is_recruiting_students' => 'Y',
        ],
        174 => 
        [
            'id' => 175,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '嘉義高工附設駕訓班',
            'address' => '嘉義市東區彌陀路１７４號',
            'telephone' => '05-2768037',
            'fax' => '05-2750592',
            'is_recruiting_students' => 'Y',
        ],
        175 => 
        [
            'id' => 176,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '新城駕訓班',
            'address' => '臺南市新營區長榮路２段３７７號',
            'telephone' => '06-6355516',
            'fax' => '06-6571688',
            'is_recruiting_students' => 'Y',
        ],
        176 => 
        [
            'id' => 177,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '南凱駕訓班',
            'address' => '臺南市安南區安中路一段８６３號',
            'telephone' => '06-2556797',
            'fax' => '06-2564807',
            'is_recruiting_students' => 'Y',
        ],
        177 => 
        [
            'id' => 178,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '志成駕訓班',
            'address' => '臺南市北區文賢路４２７號',
            'telephone' => '06-2586176',
            'fax' => '06-2586177',
            'is_recruiting_students' => 'Y',
        ],
        178 => 
        [
            'id' => 179,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '大華駕訓班',
            'address' => '雲林縣斗六市斗六市文化路９６０號',
            'telephone' => '05-5328123',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        179 => 
        [
            'id' => 180,
            'office' => '嘉義區監理所',
            'station' => '麻豆監理站',
            'name' => '力偉駕訓班',
            'address' => '臺南市新市區港墘里自由街７號',
            'telephone' => '06-5991051',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        180 => 
        [
            'id' => 181,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '東信駕訓班',
            'address' => '雲林縣麥寮鄉光復南路９５號',
            'telephone' => '05-6935080',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        181 => 
        [
            'id' => 182,
            'office' => '嘉義區監理所',
            'station' => '麻豆監理站',
            'name' => '日新駕訓班',
            'address' => '臺南市善化區坐駕里大成路８５之２號',
            'telephone' => '06-5831682',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        182 => 
        [
            'id' => 183,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '嘉聯駕訓班',
            'address' => '嘉義縣新港鄉南港村２２９號',
            'telephone' => '05-7811786',
            'fax' => '05-7810995',
            'is_recruiting_students' => 'Y',
        ],
        183 => 
        [
            'id' => 184,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '統一駕訓班',
            'address' => '臺南市永康區五王里中山東路２８９號',
            'telephone' => '06-2354211',
            'fax' => '06-3123783',
            'is_recruiting_students' => 'Y',
        ],
        184 => 
        [
            'id' => 185,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '良和駕訓班',
            'address' => '臺南市北區文賢路９９６號',
            'telephone' => '06-2590327',
            'fax' => '06-2590327',
            'is_recruiting_students' => 'N',
        ],
        185 => 
        [
            'id' => 186,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '成功駕訓班',
            'address' => '臺南市永康區中正南路５２巷６８弄６８號',
            'telephone' => '06-2828128',
            'fax' => '06-2537072',
            'is_recruiting_students' => 'Y',
        ],
        186 => 
        [
            'id' => 187,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '新馬駕訓班',
            'address' => '雲林縣東勢鄉復興村文化路３號',
            'telephone' => '05-6991234',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        187 => 
        [
            'id' => 188,
            'office' => '嘉義區監理所',
            'station' => '麻豆監理站',
            'name' => '嘉南駕訓班',
            'address' => '臺南市六甲區龜港里４９１號',
            'telephone' => '06-6982526',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        188 => 
        [
            'id' => 189,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '三立駕訓班',
            'address' => '雲林縣虎尾鎮立德路１７８號',
            'telephone' => '05-6361696',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        189 => 
        [
            'id' => 190,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '大灣駕訓班',
            'address' => '臺南市永康區西勢里廣興街１７０巷２０１號',
            'telephone' => '06-2736338',
            'fax' => '06-2736337',
            'is_recruiting_students' => 'Y',
        ],
        190 => 
        [
            'id' => 191,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '亞洲駕訓班',
            'address' => '臺南市仁德區二行里二行一路六號',
            'telephone' => '06-2663377',
            'fax' => '06-2663388',
            'is_recruiting_students' => 'Y',
        ],
        191 => 
        [
            'id' => 192,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '大榮駕訓班',
            'address' => '嘉義縣民雄鄉福興村牛稠溪５８５號',
            'telephone' => '05-2210750',
            'fax' => '05-2207302',
            'is_recruiting_students' => 'Y',
        ],
        192 => 
        [
            'id' => 193,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '學園駕訓班',
            'address' => '雲林縣斗南鎮斗南鎮中山路２１６號',
            'telephone' => '05-5974766',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        193 => 
        [
            'id' => 194,
            'office' => '嘉義區監理所',
            'station' => '麻豆監理站',
            'name' => '新榮駕訓班',
            'address' => '臺南市柳營區光福里１３２－１２號',
            'telephone' => '06-6221912',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        194 => 
        [
            'id' => 195,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '崑山駕訓班',
            'address' => '臺南市永康區復興路５２之２０１號',
            'telephone' => '06-2719899',
            'fax' => '06-2053686',
            'is_recruiting_students' => 'Y',
        ],
        195 => 
        [
            'id' => 196,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '新昇駕訓班',
            'address' => '雲林縣虎尾鎮三合里吳厝５９之６號',
            'telephone' => '05-6627100',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        196 => 
        [
            'id' => 197,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '新十全駕訓班',
            'address' => '嘉義縣布袋鎮貴舍里半月９５號',
            'telephone' => '05-3452952',
            'fax' => '05-3452953',
            'is_recruiting_students' => 'Y',
        ],
        197 => 
        [
            'id' => 198,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '三華駕訓班',
            'address' => '臺南市南區台南市金華路一段１５１號',
            'telephone' => '06-2917986',
            'fax' => '06-2917884',
            'is_recruiting_students' => 'Y',
        ],
        198 => 
        [
            'id' => 199,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '長榮駕訓班',
            'address' => '臺南市歸仁區六甲路４５０號',
            'telephone' => '06-3303300',
            'fax' => '06-3306594',
            'is_recruiting_students' => 'Y',
        ],
        199 => 
        [
            'id' => 200,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '上福駕訓班',
            'address' => '臺南市南區鯤鯓路１１９巷２８號',
            'telephone' => '06-2629967',
            'fax' => '06-2962929',
            'is_recruiting_students' => 'Y',
        ],
        200 => 
        [
            'id' => 201,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '中山駕訓班',
            'address' => '臺南市歸仁區六甲里勝利街９７弄１３４號',
            'telephone' => '06-2795353',
            'fax' => '06-3305061',
            'is_recruiting_students' => 'Y',
        ],
        201 => 
        [
            'id' => 202,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '富邦駕訓班',
            'address' => '嘉義縣水上鄉民生村忠孝街２－６號',
            'telephone' => '05-2365388',
            'fax' => '05-2842507',
            'is_recruiting_students' => 'Y',
        ],
        202 => 
        [
            'id' => 203,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '金聲駕訓班',
            'address' => '嘉義縣民雄鄉福樂村埤角２－２２２號',
            'telephone' => '05-2204147',
            'fax' => '05-2131359',
            'is_recruiting_students' => 'Y',
        ],
        203 => 
        [
            'id' => 204,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '永康駕訓班',
            'address' => '臺南市永康區中山路４５２號',
            'telephone' => '06-2037808',
            'fax' => '06-2037809',
            'is_recruiting_students' => 'Y',
        ],
        204 => 
        [
            'id' => 205,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '東泰駕訓班',
            'address' => '雲林縣四湖鄉四湖鄉蔡厝村１２２號',
            'telephone' => '05-7873899',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        205 => 
        [
            'id' => 206,
            'office' => '嘉義區監理所',
            'station' => '臺南監理站',
            'name' => '台南高工附設駕訓班',
            'address' => '臺南市永康區中山南路１９３號',
            'telephone' => '06-2027886',
            'fax' => '06-2321903',
            'is_recruiting_students' => 'Y',
        ],
        206 => 
        [
            'id' => 207,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '宏得駕訓班',
            'address' => '雲林縣虎尾鎮虎尾謓延平里下南１５號',
            'telephone' => '05-6625625',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        207 => 
        [
            'id' => 208,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '佑安駕訓班',
            'address' => '臺南市後壁區嘉田里上茄苳１２－１１２號',
            'telephone' => '06-6882002',
            'fax' => '06-6882608',
            'is_recruiting_students' => 'Y',
        ],
        208 => 
        [
            'id' => 209,
            'office' => '嘉義區監理所',
            'station' => '嘉義區監理所',
            'name' => '北昇駕訓班',
            'address' => '嘉義縣太保市過溝里三合７０１號',
            'telephone' => '05-2385656',
            'fax' => '05-2383757',
            'is_recruiting_students' => 'Y',
        ],
        209 => 
        [
            'id' => 210,
            'office' => '嘉義區監理所',
            'station' => '雲林監理站',
            'name' => '全民駕訓班',
            'address' => '雲林縣虎尾鎮林森路一段107-30號',
            'telephone' => '05-6366266',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        210 => 
        [
            'id' => 211,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '和宏駕訓班',
            'address' => '高雄市路竹區大仁路８３７號',
            'telephone' => '07-6971311',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        211 => 
        [
            'id' => 212,
            'office' => '高雄區監理所',
            'station' => '臺東監理站',
            'name' => '台東縣私立東陞駕訓班',
            'address' => '臺東縣臺東市台東市知本路２段４３０巷５６號',
            'telephone' => '089-513666',
            'fax' => '089-358315',
            'is_recruiting_students' => 'Y',
        ],
        212 => 
        [
            'id' => 213,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '東寧駕訓班',
            'address' => '屏東縣鹽埔鄉洛陽村洛寧路７６號',
            'telephone' => '08-7032285',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        213 => 
        [
            'id' => 214,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '大發駕訓班',
            'address' => '高雄市鳳山區國泰路一段１３３號',
            'telephone' => '07-7195599',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        214 => 
        [
            'id' => 215,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '標昇駕訓班',
            'address' => '屏東縣枋寮鄉中山路３５２號',
            'telephone' => '08-8713016',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        215 => 
        [
            'id' => 216,
            'office' => '高雄區監理所',
            'station' => '臺東監理站',
            'name' => '台東縣私立新生駕訓班',
            'address' => '臺東縣臺東市中興路３段５０３號',
            'telephone' => '089-226866',
            'fax' => '089-229697',
            'is_recruiting_students' => 'Y',
        ],
        216 => 
        [
            'id' => 217,
            'office' => '高雄區監理所',
            'station' => '臺東監理站',
            'name' => '台東縣私立欣興駕訓班',
            'address' => '臺東縣池上鄉新興村９鄰９２－２５號',
            'telephone' => '089-861747',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        217 => 
        [
            'id' => 218,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '九六駕訓班',
            'address' => '屏東縣新園鄉五房村龍州路４７－８號',
            'telephone' => '08-8691796',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        218 => 
        [
            'id' => 219,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '高大駕訓班',
            'address' => '高雄市大寮區江山里江山路７９－２號',
            'telephone' => '07-7014415',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        219 => 
        [
            'id' => 220,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '潮州汽車駕駛人訓練班',
            'address' => '屏東縣潮州鎮太平路666號',
            'telephone' => '08-7800111',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        220 => 
        [
            'id' => 221,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '雙園駕訓班',
            'address' => '高雄市林園區後厝路６巷１１號',
            'telephone' => '07-6412836',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        221 => 
        [
            'id' => 222,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '榮仁駕訓班',
            'address' => '高雄市鳳山區武營路402號',
            'telephone' => '07-7716228',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        222 => 
        [
            'id' => 223,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '合誼駕訓班',
            'address' => '屏東縣屏東市海豐街６９巷１４３號',
            'telephone' => '08-7377375',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        223 => 
        [
            'id' => 224,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '有能駕訓班',
            'address' => '屏東縣屏東市忠孝路３２６號',
            'telephone' => '08-7666186',
            'fax' => '',
            'is_recruiting_students' => 'N',
        ],
        224 => 
        [
            'id' => 225,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '同安駕訓班',
            'address' => '高雄市岡山區致遠路附８８號',
            'telephone' => '07-6267678',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        225 => 
        [
            'id' => 226,
            'office' => '高雄區監理所',
            'station' => '旗山監理站',
            'name' => '永全駕訓班',
            'address' => '高雄市燕巢區安招里安招路1066之7號',
            'telephone' => '07-6165256',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        226 => 
        [
            'id' => 227,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '南訓駕訓班',
            'address' => '高雄市橋頭區里林東路公路巷１２０號',
            'telephone' => '07-6117101',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        227 => 
        [
            'id' => 228,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '麟洛駕訓班',
            'address' => '屏東縣麟洛鄉新田村民族路５１６號',
            'telephone' => '08-7239693',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        228 => 
        [
            'id' => 229,
            'office' => '高雄區監理所',
            'station' => '旗山監理站',
            'name' => '上鼎駕訓班',
            'address' => '高雄市內門區中正路２２９巷６５號',
            'telephone' => '07-6673877',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        229 => 
        [
            'id' => 230,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '豐隆駕駛人訓練班',
            'address' => '屏東縣屏東市屏東市復興南路一段５０５巷３２號',
            'telephone' => '08-7539588',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        230 => 
        [
            'id' => 231,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '高旗駕訓班',
            'address' => '高雄市鳳山區鳳仁路９０號',
            'telephone' => '07-7467593',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        231 => 
        [
            'id' => 232,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '光隆駕訓班',
            'address' => '高雄市鳳山區中崙一路３３號',
            'telephone' => '07-7555559',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        232 => 
        [
            'id' => 233,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '高??駕訓班',
            'address' => '高雄市大寮區會結路１－３５號',
            'telephone' => '07-7879777',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        233 => 
        [
            'id' => 234,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '永大駕訓班',
            'address' => '高雄市路竹區永華路200號',
            'telephone' => '07-6976117',
            'fax' => '07-7614853',
            'is_recruiting_students' => 'Y',
        ],
        234 => 
        [
            'id' => 235,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '弘全駕訓班',
            'address' => '屏東縣南州鄉屏東縣南州鄉同安村三千路５６號',
            'telephone' => '08-8644108',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        235 => 
        [
            'id' => 236,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '東港駕訓班',
            'address' => '屏東縣東港鎮沿海路８０號',
            'telephone' => '08-8327566',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        236 => 
        [
            'id' => 237,
            'office' => '高雄區監理所',
            'station' => '屏東監理站',
            'name' => '超?駕訓班',
            'address' => '屏東縣潮州鎮彭城里彭城路233巷55號',
            'telephone' => '08-7871408',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        237 => 
        [
            'id' => 238,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '永慶駕訓班',
            'address' => '高雄市岡山區大莊里大莊路６０巷２５號',
            'telephone' => '07-6285299',
            'fax' => '07-7614852',
            'is_recruiting_students' => 'Y',
        ],
        238 => 
        [
            'id' => 239,
            'office' => '高雄區監理所',
            'station' => '旗山監理站',
            'name' => '同聲駕訓班',
            'address' => '高雄市內門區內豐里內埔１３９號',
            'telephone' => '07-6614277',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
        239 => 
        [
            'id' => 240,
            'office' => '高雄區監理所',
            'station' => '高雄區監理所',
            'name' => '大崗山駕訓班',
            'address' => '高雄市阿蓮區建國２０之１８號',
            'telephone' => '07-6312513',
            'fax' => '',
            'is_recruiting_students' => 'Y',
        ],
    ]);
    }
}