<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaiwanMovieTheatersTableSeeder extends Seeder
{
    /**
     * Run the database seeders.
     */
    public function run(): void
    {
        DB::table('taiwan_movie_theaters')->delete();
        DB::table('taiwan_movie_theaters')->insert([
            0 => 
            [
                'city' => '台北市',
                'business_name' => '國賓大戲院',
                'company_name' => '國賓企業股份有限公司',
                'national_id_no' => '15324301',
                'total_rooms' => 3,
                'address' => '台北市成都路88號',
                'telephone' => '02-23611223',
                'remark' => '',
            ],
            1 => 
            [
                'city' => '台北市',
                'business_name' => '台北新光影城',
                'company_name' => '新光三越百貨股份有限公司台北獅子林分公司',
                'national_id_no' => '70749633',
                'total_rooms' => 3,
                'address' => '台北市萬華區西寧南路36號4樓',
                'telephone' => '02-23146668',
                'remark' => '',
            ],
            2 => 
            [
                'city' => '台北市',
                'business_name' => '樂聲大戲院',
                'company_name' => '樂聲大戲院股份有限公司',
                'national_id_no' => '3583704',
                'total_rooms' => 4,
                'address' => '台北市萬華區武昌街2段85號1~5樓',
                'telephone' => '02-23118628',
                'remark' => '',
            ],
            3 => 
            [
                'city' => '台北市',
                'business_name' => '台北日新威秀影城',
                'company_name' => '王牌日新大戲院',
                'national_id_no' => '80694074',
                'total_rooms' => 4,
                'address' => '台北市武昌路2段87號1~2樓',
                'telephone' => '02-23315256',
                'remark' => '',
            ],
            4 => 
            [
                'city' => '台北市',
                'business_name' => 'in89豪華數位影城',
                'company_name' => '豪華大戲院股份有限公司',
                'national_id_no' => '3539102',
                'total_rooms' => 3,
                'address' => '台北市武昌街2段89號',
                'telephone' => '02-23315077',
                'remark' => '',
            ],
            5 => 
            [
                'city' => '台北市',
                'business_name' => 'in89豪華數位影城',
                'company_name' => '映捌玖數位影城有限公司',
                'national_id_no' => '54186685',
                'total_rooms' => 4,
                'address' => '台北市武昌街2段89號',
                'telephone' => '02-23315077',
                'remark' => '',
            ],
            6 => 
            [
                'city' => '台北市',
                'business_name' => '今日秀泰影城',
                'company_name' => '萬華企業股份有限公司',
                'national_id_no' => '15415013',
                'total_rooms' => 10,
                'address' => '台北市峨嵋街52號4.6.8樓',
                'telephone' => '02-23814272',
                'remark' => '',
            ],
            7 => 
            [
                'city' => '台北市',
                'business_name' => '喜滿客絕色電影城',
                'company_name' => '絕色影城股份有限公司',
                'national_id_no' => '80192629',
                'total_rooms' => 9,
                'address' => '台北市萬華區漢中街52號8至11樓',
                'telephone' => '02-23811339',
                'remark' => '',
            ],
            8 => 
            [
                'city' => '台北市',
                'business_name' => '真善美劇院',
                'company_name' => '中影股份有限公司真善美分公司',
                'national_id_no' => '97293474',
                'total_rooms' => 2,
                'address' => '台北市漢中街116號7樓',
                'telephone' => '02-23312270',
                'remark' => '',
            ],
            9 => 
            [
                'city' => '台北市',
                'business_name' => '光點',
                'company_name' => '三視多媒體網路股份有限公司',
                'national_id_no' => '70655641',
                'total_rooms' => 1,
                'address' => '台北市中山北路2段18號',
                'telephone' => '02-25117786',
                'remark' => '',
            ],
            10 => 
            [
                'city' => '台北市',
                'business_name' => '華山電影藝術館',
                'company_name' => '三三電影製作有限公司',
                'national_id_no' => '15975423',
                'total_rooms' => 2,
                'address' => '台北市中正區八德路一段1號 ',
                'telephone' => '02-23940622',
                'remark' => '',
            ],
            11 => 
            [
                'city' => '台北市',
                'business_name' => '台北京站威秀影城',
                'company_name' => '威秀影城股份有限公司京站分公司',
                'national_id_no' => '28984678',
                'total_rooms' => 9,
                'address' => '台北市大同區華陰街34號5、6樓',
                'telephone' => '02-25525511',
                'remark' => '',
            ],
            12 => 
            [
                'city' => '台北市',
                'business_name' => '朝代大戲院',
                'company_name' => '朝代大戲院有限公司',
                'national_id_no' => '86138031',
                'total_rooms' => 2,
                'address' => '台北市民權西路136號4樓',
                'telephone' => '02-25571380',
                'remark' => '',
            ],
            13 => 
            [
                'city' => '台北市',
                'business_name' => '龍祥百老匯影城',
                'company_name' => '龍祥育樂多媒體股份有限公司臺北分公司',
                'national_id_no' => '16289859',
                'total_rooms' => 7,
                'address' => '台北市文山區羅斯福路四段200號3、4、5樓',
                'telephone' => '02-86636128',
                'remark' => '',
            ],
            14 => 
            [
                'city' => '台北市',
                'business_name' => '東南亞電影廣場',
                'company_name' => '東南亞育樂股份有限公司',
                'national_id_no' => '18748606',
                'total_rooms' => 6,
                'address' => '台北市羅斯福路4段136巷3號',
                'telephone' => '02-23678999',
                'remark' => '',
            ],
            15 => 
            [
                'city' => '台北市',
                'business_name' => '湳山戲院',
                'company_name' => '南山大戲院',
                'national_id_no' => '4920795',
                'total_rooms' => 4,
                'address' => '台北市通化街24巷1號',
                'telephone' => '02-27023130',
                'remark' => '',
            ],
            16 => 
            [
                'city' => '台北市',
                'business_name' => '梅花數位影院',
                'company_name' => '中影股份有限公司梅花分公司',
                'national_id_no' => '97302430',
                'total_rooms' => 2,
                'address' => '台北市和平東路三段63號2樓',
                'telephone' => '02-27326968',
                'remark' => '',
            ],
            17 => 
            [
                'city' => '台北市',
                'business_name' => '總督大戲院',
                'company_name' => '船興企業股份有限公司',
                'national_id_no' => '5148262',
                'total_rooms' => 1,
                'address' => '台北市松山區長安東路2段219號3、4樓',
                'telephone' => '02-27415991',
                'remark' => '',
            ],
            18 => 
            [
                'city' => '台北市',
                'business_name' => '首都戲院',
                'company_name' => '龍子電影事業股份有限公司',
                'national_id_no' => '21235165',
                'total_rooms' => 1,
                'address' => '台北市松山區長安東路2段219號2、3樓',
                'telephone' => '02-27415991',
                'remark' => '',
            ],
            19 => 
            [
                'city' => '台北市',
                'business_name' => '喜滿客京華影城',
                'company_name' => '喜滿客京華影城股份有限公司',
                'national_id_no' => '16792611',
                'total_rooms' => 13,
                'address' => '台北市松山區八德路4段138號B1、B2、B3',
                'telephone' => '02-37622001',
                'remark' => '',
            ],
            20 => 
            [
                'city' => '台北市',
                'business_name' => '新民生戲院',
                'company_name' => '民生戲院股份有限公司',
                'national_id_no' => '53563725',
                'total_rooms' => 2,
                'address' => '台北市松山區民生東路五段190號3樓',
                'telephone' => '02-27653373',
                'remark' => '',
            ],
            21 => 
            [
                'city' => '台北市',
                'business_name' => '國賓影城@台北長春廣場',
                'company_name' => '國元影業股份有限公司長春分公司',
                'national_id_no' => '25122923',
                'total_rooms' => 2,
                'address' => '台北市中山區長春路172號2至3樓、地下1樓',
                'telephone' => '02-25155757',
                'remark' => '',
            ],
            22 => 
            [
                'city' => '台北市',
                'business_name' => '國賓影城@台北長春廣場',
                'company_name' => '國元影業股份有限公司',
                'national_id_no' => '25116865',
                'total_rooms' => 13,
                'address' => '台北市中山區長春路176號2F、3F、B2、B3',
                'telephone' => '02-25155757',
                'remark' => '',
            ],
            23 => 
            [
                'city' => '台北市',
                'business_name' => '欣欣秀泰影城',
                'company_name' => '欣欣大眾市場股份有限公司',
                'national_id_no' => '11364230',
                'total_rooms' => 14,
                'address' => '台北市中山區林森北路247號3、4、5樓',
                'telephone' => '02-25371889',
                'remark' => '',
            ],
            24 => 
            [
                'city' => '台北市',
                'business_name' => '國賓影城@微風廣場',
                'company_name' => '國賓影城股份有限公司微風分公司',
                'national_id_no' => '70795468',
                'total_rooms' => 6,
                'address' => '台北市松山區復興南路1段39號8、10樓',
                'telephone' => '02-87721234',
                'remark' => '',
            ],
            25 => 
            [
                'city' => '台北市',
                'business_name' => '美麗華大直影城',
                'company_name' => '美麗華娛樂股份有限公司',
                'national_id_no' => '16604391',
                'total_rooms' => 10,
                'address' => '台北市敬業3路22號6樓',
                'telephone' => '02-85022208',
                'remark' => '',
            ],
            26 => 
            [
                'city' => '台北市',
                'business_name' => '哈拉影城',
                'company_name' => '哈拉影城有限公司',
                'national_id_no' => '70436436',
                'total_rooms' => 8,
                'address' => '台北市內湖區康寧路3段72號2樓之1、之2、3樓之1、之2',
                'telephone' => '02-26322693',
                'remark' => '',
            ],
            27 => 
            [
                'city' => '台北市',
                'business_name' => '佳佳來來戲院',
                'company_name' => '弘美育樂股份有限公司',
                'national_id_no' => '4873385',
                'total_rooms' => 5,
                'address' => '台北市文山區羅斯福路六段403號4樓',
                'telephone' => '02-29346494',
                'remark' => '',
            ],
            28 => 
            [
                'city' => '台北市',
                'business_name' => '華威天母影城',
                'company_name' => '華威影城有限公司',
                'national_id_no' => '27310984',
                'total_rooms' => 8,
                'address' => '台北市士林區忠誠路2段202號4~8樓',
                'telephone' => '02-28763300',
                'remark' => '',
            ],
            29 => 
            [
                'city' => '台北市',
                'business_name' => '台北信義威秀影城',
                'company_name' => '威秀影城股份有限公司信義分公司',
                'national_id_no' => '16431011',
                'total_rooms' => 17,
                'address' => '台北市信義區松壽路18號2、3樓， 20號3樓',
                'telephone' => '02-87805566',
                'remark' => '',
            ],
            30 => 
            [
                'city' => '台北市',
                'business_name' => '誠品電影院',
                'company_name' => '誠品股份有限公司',
                'national_id_no' => '23155531',
                'total_rooms' => 3,
                'address' => '台北市信義區菸廠路80號B2',
                'telephone' => '02-66365888',
                'remark' => '',
            ],
            31 => 
            [
                'city' => '台北市',
                'business_name' => '喜樂時代影城',
                'company_name' => '喜樂時代影城股份有限公司南港分公司',
                'national_id_no' => '42828452',
                'total_rooms' => 25,
                'address' => '臺北市南港區忠孝東路7段299號11、12、13、14樓',
                'telephone' => '02-27888185',
                'remark' => '',
            ],
            32 => 
            [
                'city' => '台北市',
                'business_name' => 'MUVIE CINEMAS威秀影城',
                'company_name' => '威秀影城股份有限公司松仁分公司',
                'national_id_no' => '54915305',
                'total_rooms' => 8,
                'address' => '臺北市信義區松仁路58號10、11、12、13樓',
                'telephone' => '02-87800800',
                'remark' => '',
            ],
            33 => 
            [
                'city' => '新北市',
                'business_name' => '天台戲院',
                'company_name' => '天台戲院股份有限公司',
                'national_id_no' => '35078600',
                'total_rooms' => 5,
                'address' => '新北市三重區重新路二段78號4樓',
                'telephone' => '02-29784614',
                'remark' => '',
            ],
            34 => 
            [
                'city' => '新北市',
                'business_name' => '板橋秀泰影城',
                'company_name' => '板球秀泰影城有限公司',
                'national_id_no' => '54015819',
                'total_rooms' => 17,
                'address' => '新北市板橋區縣民大道二段3號2-4樓',
                'telephone' => '02-29685588',
                'remark' => '',
            ],
            35 => 
            [
                'city' => '新北市',
                'business_name' => '板橋大遠百威秀影城',
                'company_name' => '威秀影城股份有限公司板橋分公司',
                'national_id_no' => '53019247',
                'total_rooms' => 9,
                'address' => '新北市板橋區新站路28號10樓',
                'telephone' => '02-77386608',
                'remark' => '',
            ],
            36 => 
            [
                'city' => '新北市',
                'business_name' => '林園電影城',
                'company_name' => '林園電影城戲院',
                'national_id_no' => '8563729',
                'total_rooms' => 3,
                'address' => '新北市板橋區府中路175號3樓',
                'telephone' => '02-29606099',
                'remark' => '',
            ],
            37 => 
            [
                'city' => '新北市',
                'business_name' => '林園電影城',
                'company_name' => '華麗電影院',
                'national_id_no' => '95891495',
                'total_rooms' => 2,
                'address' => '新北市板橋區府中路175號5樓',
                'telephone' => '02-29605333',
                'remark' => '',
            ],
            38 => 
            [
                'city' => '新北市',
                'business_name' => '鴻金寶麻吉影城',
                'company_name' => '萬念福開發事業股份有限公司',
                'national_id_no' => '89578933',
                'total_rooms' => 5,
                'address' => '新北市新莊區民安路188巷5號4樓',
                'telephone' => '02-22070222',
                'remark' => '',
            ],
            39 => 
            [
                'city' => '新北市',
                'business_name' => '國賓影城@中和環球購物中心',
                'company_name' => '國賓影城股份有限公司中和分公司',
                'national_id_no' => '27977191',
                'total_rooms' => 7,
                'address' => '新北市中和區中山路3段122號4樓',
                'telephone' => '02-22268088',
                'remark' => '',
            ],
            40 => 
            [
                'city' => '新北市',
                'business_name' => '國賓影城@林口昕境廣場',
                'company_name' => '國賓影城股份有限公司林口分公司',
                'national_id_no' => '24935022',
                'total_rooms' => 8,
                'address' => '新北市林口區文化三路一段402巷2號4樓',
                'telephone' => '02-26080011',
                'remark' => '',
            ],
            41 => 
            [
                'city' => '新北市',
                'business_name' => '國賓影城@新莊晶冠廣場',
                'company_name' => '國賓影城股份有限公司新莊分公司',
                'national_id_no' => '24964285',
                'total_rooms' => 13,
                'address' => '新北市新莊區五工路66號3樓及4樓',
                'telephone' => '02-85216517',
                'remark' => '',
            ],
            42 => 
            [
                'city' => '新北市',
                'business_name' => '林口MITSUI OUTLET PARK威秀影城',
                'company_name' => '威秀影城股份有限公司新北林口分公司',
                'national_id_no' => '24808911',
                'total_rooms' => 9,
                'address' => '新北市林口區文化三路1段356號3樓',
                'telephone' => '02-26084750',
                'remark' => '',
            ],
            43 => 
            [
                'city' => '新北市',
                'business_name' => '樹林秀泰影城',
                'company_name' => '樹林秀泰影城股份有限公司',
                'national_id_no' => '69421836',
                'total_rooms' => 12,
                'address' => '新北市樹林區樹新路40之6號',
                'telephone' => '02-26868769',
                'remark' => '',
            ],
            44 => 
            [
                'city' => '新北市',
                'business_name' => '土城秀泰影城',
                'company_name' => '土城秀泰影城股份有限公司',
                'national_id_no' => '66629312',
                'total_rooms' => 11,
                'address' => '新北市土城區學府路2段210號1樓',
                'telephone' => '02-22603398',
                'remark' => '',
            ],
            45 => 
            [
                'city' => '新北市',
                'business_name' => '美麗新淡海影城',
                'company_name' => '美麗新娛樂股份有限公司淡海分公司',
                'national_id_no' => '50878692',
                'total_rooms' => 9,
                'address' => '新北市淡水區義山路2段303號2～4樓',
                'telephone' => '02-77050899',
                'remark' => '',
            ],
            46 => 
            [
                'city' => '新北市',
                'business_name' => '國賓影城@淡水禮萊廣場',
                'company_name' => '國賓影城股份有限公司淡水分公司',
                'national_id_no' => '82910127',
                'total_rooms' => 8,
                'address' => '新北市淡水區中正路一段2號',
                'telephone' => '02-26260707',
                'remark' => '',
            ],
            47 => 
            [
                'city' => '台中市',
                'business_name' => '全球影城',
                'company_name' => '亮威股份有限公司',
                'national_id_no' => '97219643',
                'total_rooms' => 7,
                'address' => '台中市中區中華路一段1之1號，B1-5, B2-5, 3F-1, 4F-1',
                'telephone' => '04-22242588',
                'remark' => '',
            ],
            48 => 
            [
                'city' => '台中市',
                'business_name' => '日日新大戲院',
                'company_name' => '日日新國際商業股份有限公司',
                'national_id_no' => '97265890',
                'total_rooms' => 5,
                'address' => '台中市中區中華路一段58號1至10樓',
                'telephone' => '04-22223138',
                'remark' => '',
            ],
            49 => 
            [
                'city' => '台中市',
                'business_name' => '萬代福戲院',
                'company_name' => '桂冠育樂股份有限公司',
                'national_id_no' => '52664555',
                'total_rooms' => 5,
                'address' => '台中市中區公園路38號3樓、4樓、B1',
                'telephone' => '04-22265270',
                'remark' => '',
            ],
            50 => 
            [
                'city' => '台中市',
                'business_name' => '豐源國際影城',
                'company_name' => '豐源育樂有限公司',
                'national_id_no' => '5697668',
                'total_rooms' => 4,
                'address' => '台中市豐原區中正路137號1、2、3樓',
                'telephone' => '04-25260036',
                'remark' => '',
            ],
            51 => 
            [
                'city' => '台中市',
                'business_name' => '台中大遠百威秀影城 ',
                'company_name' => '威秀影城股份有限公司惠中分公司',
                'national_id_no' => '53018958',
                'total_rooms' => 7,
                'address' => '台中市西屯區台中港路二段105號13樓',
                'telephone' => '04-22588511',
                'remark' => '',
            ],
            52 => 
            [
                'city' => '台中市',
                'business_name' => '台中新光影城',
                'company_name' => '新光影城股份有限公司台中中港分公司',
                'national_id_no' => '70784899',
                'total_rooms' => 8,
                'address' => '台中市西屯區台中港路二段111號13、14樓',
                'telephone' => '04-22589911',
                'remark' => '',
            ],
            53 => 
            [
                'city' => '台中市',
                'business_name' => '台中新時代威秀影城',
                'company_name' => '威秀影城股份有限公司台中東區分公司',
                'national_id_no' => '12942667',
                'total_rooms' => 9,
                'address' => '台中市東區復興路4段186號4、5樓',
                'telephone' => '04-36085566 ',
                'remark' => '',
            ],
            54 => 
            [
                'city' => '台中市',
                'business_name' => '親親大戲院',
                'company_name' => '親親育樂股份有限公司',
                'national_id_no' => '22068524',
                'total_rooms' => 7,
                'address' => '台中市北區錦洲里北屯路14號',
                'telephone' => '04-22319111',
                'remark' => '',
            ],
            55 => 
            [
                'city' => '台中市',
                'business_name' => '台中Tiger City威秀影城',
                'company_name' => '威秀影城股份有限公司台中西屯區分公司',
                'national_id_no' => '12963016',
                'total_rooms' => 10,
                'address' => '台中市西屯區河南路三段120-1號4樓',
                'telephone' => '04-36065566',
                'remark' => '',
            ],
            56 => 
            [
                'city' => '台中市',
                'business_name' => '時代戲院',
                'company_name' => '時代戲院',
                'national_id_no' => '56083517',
                'total_rooms' => 2,
                'address' => '台中市清水區文昌里光復街65號3樓',
                'telephone' => '04-26222206',
                'remark' => '',
            ],
            57 => 
            [
                'city' => '台中市',
                'business_name' => '華威台中影城',
                'company_name' => '華鵬影城股份有限公司',
                'national_id_no' => '54229636',
                'total_rooms' => 6,
                'address' => '臺中市西區臺灣大道二段459號17、18、19樓',
                'telephone' => '04-23103768',
                'remark' => '',
            ],
            58 => 
            [
                'city' => '台中市',
                'business_name' => '凱擘影城',
                'company_name' => '凱擘影藝股份有限公司台中東區分公司',
                'national_id_no' => '51160612',
                'total_rooms' => 9,
                'address' => '台中市東區復興路4段186號4、5樓',
                'telephone' => '04-36080900',
                'remark' => '',
            ],
            59 => 
            [
                'city' => '台中市',
                'business_name' => '台中站前秀泰影城',
                'company_name' => '台中站前秀泰影城股份有限公司',
                'national_id_no' => '60299530',
                'total_rooms' => 17,
                'address' => '台中市東區南京路76號',
                'telephone' => '04-22117988',
                'remark' => '',
            ],
            60 => 
            [
                'city' => '台中市',
                'business_name' => '台中文心秀泰影城',
                'company_name' => '台中文心秀泰影城股份有限公司',
                'national_id_no' => '50816675',
                'total_rooms' => 16,
                'address' => '台中市南屯區文心南路289號7～8樓',
                'telephone' => '04-24735989',
                'remark' => '',
            ],
            61 => 
            [
                'city' => '台中市',
                'business_name' => '台中麗寶秀泰影城',
                'company_name' => '麗寶秀泰影城股份有限公司',
                'national_id_no' => '85040051',
                'total_rooms' => 10,
                'address' => '台中市后里區月眉東路二段181號3樓',
                'telephone' => '04-2558-7180',
                'remark' => '',
            ],
            62 => 
            [
                'city' => '台南市',
                'business_name' => '全美戲院',
                'company_name' => '全美戲院有限公司',
                'national_id_no' => '68209998',
                'total_rooms' => 2,
                'address' => '台南市永福路二段187號',
                'telephone' => '06-2224726',
                'remark' => '',
            ],
            63 => 
            [
                'city' => '台南市',
                'business_name' => '今日戲院',
                'company_name' => '今日大戲院有限公司',
                'national_id_no' => '13125398',
                'total_rooms' => 1,
                'address' => '台南市中正路249號2樓',
                'telephone' => '06-2222265',
                'remark' => '',
            ],
            64 => 
            [
                'city' => '台南市',
                'business_name' => '台南大遠百威秀影城',
                'company_name' => '威秀影城股份有限公司台南分公司',
                'national_id_no' => '80332430',
                'total_rooms' => 9,
                'address' => '台南市公園路60號5~13樓',
                'telephone' => '06-6005566',
                'remark' => '',
            ],
            65 => 
            [
                'city' => '台南市',
                'business_name' => '台南新光影城',
                'company_name' => '新光影城股份有限公司台南西門分公司',
                'national_id_no' => '80511807',
                'total_rooms' => 8,
                'address' => '台南市西門路一段658號9、10、11、12樓',
                'telephone' => '06-3031260',
                'remark' => '',
            ],
            66 => 
            [
                'city' => '台南市',
                'business_name' => '國賓影城@台南國賓廣場',
                'company_name' => '國賓影城股份有限公司台南中華分公司',
                'national_id_no' => '70826912',
                'total_rooms' => 5,
                'address' => '台南市中華東路一段66-70號',
                'telephone' => '06-2347166',
                'remark' => '',
            ],
            67 => 
            [
                'city' => '台南市',
                'business_name' => '國賓影城@台南國賓廣場',
                'company_name' => '國賓影城股份有限公司台南東區分公司',
                'national_id_no' => '68071157',
                'total_rooms' => 7,
                'address' => '台南市中華東路一段96號B1-16',
                'telephone' => '06-2347166',
                'remark' => '',
            ],
            68 => 
            [
                'city' => '台南市',
                'business_name' => '南台影城',
                'company_name' => '南台育樂事業有限公司',
                'national_id_no' => '68456929',
                'total_rooms' => 5,
                'address' => '台南市友愛街317號',
                'telephone' => '06-2287581',
                'remark' => '',
            ],
            69 => 
            [
                'city' => '台南市',
                'business_name' => '麻豆戲院',
                'company_name' => '麻豆戲院',
                'national_id_no' => '87689080',
                'total_rooms' => 2,
                'address' => '台南市麻豆區興中路106號3樓之1',
                'telephone' => '06-5722159',
                'remark' => '',
            ],
            70 => 
            [
                'city' => '台南市',
                'business_name' => '台南南紡夢時代威秀影城',
                'company_name' => '威秀影城股份有限公司台南東區分公司',
                'national_id_no' => '54393381',
                'total_rooms' => 10,
                'address' => '台南市東區中華東路一段366號5樓',
                'telephone' => '06-2372255',
                'remark' => '',
            ],
            71 => 
            [
                'city' => '台南市',
                'business_name' => '台南真善美劇院',
                'company_name' => '中影股份有限公司台南延平分公司',
                'national_id_no' => '51446933',
                'total_rooms' => 5,
                'address' => '台南市中西區西門路二段230號4樓',
                'telephone' => '06-2229768',
                'remark' => '',
            ],
            72 => 
            [
                'city' => '台南市',
                'business_name' => '台南仁德秀泰影城',
                'company_name' => '台南仁德秀泰影城股份有限公司',
                'national_id_no' => '85079837',
                'total_rooms' => 6,
                'address' => '臺南市仁德區仁愛里大同路三段759號2樓',
                'telephone' => '06-2691889',
                'remark' => '',
            ],
            73 => 
            [
                'city' => '高雄市',
                'business_name' => '喜滿客夢時代影城',
                'company_name' => '喜滿客京華城股份有限公司夢時代分公司',
                'national_id_no' => '28474605',
                'total_rooms' => 12,
                'address' => '高雄市三民區十全一路161號地下1、2樓、2~5樓',
                'telephone' => '07-9702001',
                'remark' => '',
            ],
            74 => 
            [
                'city' => '高雄市',
                'business_name' => '高雄大遠百威秀影城',
                'company_name' => '威秀影城股份有限公司高雄分公司',
                'national_id_no' => '12873991',
                'total_rooms' => 16,
                'address' => '高雄市苓雅區三多四路21號13-16樓',
                'telephone' => '07-3345566',
                'remark' => '',
            ],
            75 => 
            [
                'city' => '高雄市',
                'business_name' => '奧斯卡3D數位影城',
                'company_name' => '東王大戲院股份有限公司',
                'national_id_no' => '28293843',
                'total_rooms' => 3,
                'address' => '高雄市新興區仁智街287號B1.3樓',
                'telephone' => '07-2412128',
                'remark' => '',
            ],
            76 => 
            [
                'city' => '高雄市',
                'business_name' => '奧斯卡3D數位影城',
                'company_name' => '大西洋成股份有限公司',
                'national_id_no' => '28294792',
                'total_rooms' => 2,
                'address' => '高雄市新興區仁智街287號2樓',
                'telephone' => '07-2412128',
                'remark' => '',
            ],
            77 => 
            [
                'city' => '高雄市',
                'business_name' => '奧斯卡3D數位影城',
                'company_name' => '西華戲院股份有限公司',
                'national_id_no' => '28294152',
                'total_rooms' => 5,
                'address' => '高雄市新興區仁智街287號3.4樓',
                'telephone' => '07-2412128',
                'remark' => '',
            ],
            78 => 
            [
                'city' => '高雄市',
                'business_name' => '環球影城',
                'company_name' => '星球育樂有限公司',
                'national_id_no' => '16300355',
                'total_rooms' => 9,
                'address' => '高雄市苓雅區大順三路108號3至4樓',
                'telephone' => '07-7220066',
                'remark' => '',
            ],
            79 => 
            [
                'city' => '高雄市',
                'business_name' => '美奇萊影城',
                'company_name' => '美奇萊育樂股份有限公司',
                'national_id_no' => '27222357',
                'total_rooms' => 8,
                'address' => '高雄市前鎮區中華五路789號11、12樓',
                'telephone' => '07-3210663',
                'remark' => '',
            ],
            80 => 
            [
                'city' => '高雄市',
                'business_name' => '十全電影院',
                'company_name' => '來來大戲院',
                'national_id_no' => '81850446',
                'total_rooms' => 1,
                'address' => '高雄市三民區十全二路21號2樓',
                'telephone' => '07-3117141',
                'remark' => '',
            ],
            81 => 
            [
                'city' => '高雄市',
                'business_name' => '十全電影院',
                'company_name' => '博愛大戲院',
                'national_id_no' => '75978156',
                'total_rooms' => 1,
                'address' => '高雄市三民區十全二路21號4-5樓',
                'telephone' => '07-3117141',
                'remark' => '',
            ],
            82 => 
            [
                'city' => '高雄市',
                'business_name' => '十全電影院',
                'company_name' => '錦元大戲院',
                'national_id_no' => '75978135',
                'total_rooms' => 1,
                'address' => '高雄市三民區十全二路21號6樓',
                'telephone' => '07-3117141',
                'remark' => '',
            ],
            83 => 
            [
                'city' => '高雄市',
                'business_name' => '十全電影院',
                'company_name' => '威尼斯戲院',
                'national_id_no' => '18451569',
                'total_rooms' => 1,
                'address' => '高雄市三民區十全二路21號8樓',
                'telephone' => '07-3117141',
                'remark' => '',
            ],
            84 => 
            [
                'city' => '高雄市',
                'business_name' => '十全電影院',
                'company_name' => '每益大戲院',
                'national_id_no' => '26022036',
                'total_rooms' => 1,
                'address' => '高雄市三民區十全二路21號9樓',
                'telephone' => '07-3117141',
                'remark' => '',
            ],
            85 => 
            [
                'city' => '高雄市',
                'business_name' => '岡山統一大戲院',
                'company_name' => '國琪育樂有限公司',
                'national_id_no' => '7911799',
                'total_rooms' => 3,
                'address' => '高雄市岡山區壽天路103之18號5樓',
                'telephone' => '07-6223300',
                'remark' => '',
            ],
            86 => 
            [
                'city' => '高雄市',
                'business_name' => '國賓影城@高雄義大世界',
                'company_name' => '國賓影城股份有限公司高雄義大分公司',
                'national_id_no' => '25113086',
                'total_rooms' => 10,
                'address' => '高雄市大樹區學城路一段12號3樓、4樓',
                'telephone' => '07-6568368',
                'remark' => '',
            ],
            87 => 
            [
                'city' => '高雄市',
                'business_name' => '台鋁 MLD Cinema',
                'company_name' => '都會生活開發股份有限公司',
                'national_id_no' => '53197354',
                'total_rooms' => 8,
                'address' => '高雄市前鎮區忠勤路8號',
                'telephone' => '07-5365388',
                'remark' => '',
            ],
            88 => 
            [
                'city' => '高雄市',
                'business_name' => ' in89駁二電影院',
                'company_name' => '映捌玖數位影城有限公司高雄分公司',
                'national_id_no' => '42823415',
                'total_rooms' => 7,
                'address' => '高雄市鹽埕區大勇路5之1號及5之2號',
                'telephone' => '07-9766088',
                'remark' => '',
            ],
            89 => 
            [
                'city' => '高雄市',
                'business_name' => '國賓影城@高雄大魯閣草衙道',
                'company_name' => '國賓影城股份有限公司高雄草衙道分公司',
                'national_id_no' => '43724883',
                'total_rooms' => 10,
                'address' => '高雄市前鎮區中山四路100號3樓',
                'telephone' => '07-1933611',
                'remark' => '',
            ],
            90 => 
            [
                'city' => '高雄市',
                'business_name' => '高雄大立in89豪華影城',
                'company_name' => '豪華大戲院股份有限公司高雄分公司',
                'national_id_no' => '82816256',
                'total_rooms' => 8,
                'address' => '高雄市前金區五福三路57號9～10樓',
                'telephone' => '07- 2166189',
                'remark' => '',
            ],
            91 => 
            [
                'city' => '基隆縣',
                'business_name' => '基隆秀泰影城',
                'company_name' => '秀泰電影城',
                'national_id_no' => '9852233',
                'total_rooms' => 7,
                'address' => '基隆市中正區信一路177號7-10樓',
                'telephone' => '02-24212388',
                'remark' => '',
            ],
            92 => 
            [
                'city' => '桃園市',
                'business_name' => '美麗華台茂影城',
                'company_name' => '歡影城股份有限公司',
                'national_id_no' => '16741796',
                'total_rooms' => 14,
                'address' => '桃園市蘆竹區南崁路一段112號7、8樓',
                'telephone' => '03-3113123',
                'remark' => '',
            ],
            93 => 
            [
                'city' => '桃園市',
                'business_name' => 'in89統領影城',
                'company_name' => '統領戲院',
                'national_id_no' => '16741796',
                'total_rooms' => 4,
                'address' => '桃園市桃園區中正路56號3樓、5樓',
                'telephone' => '03-3329398',
                'remark' => '',
            ],
            94 => 
            [
                'city' => '桃園市',
                'business_name' => '星橋國際影城',
                'company_name' => '星橋電影有限公司',
                'national_id_no' => '36408571',
                'total_rooms' => 16,
                'address' => '桃園市中壢區中園路2段501號4、5、6、7樓',
                'telephone' => '03-4680100',
                'remark' => '',
            ],
            95 => 
            [
                'city' => '桃園市',
                'business_name' => '威尼斯影城',
                'company_name' => '威尼斯影城股份有限公司',
                'national_id_no' => '12690563',
                'total_rooms' => 10,
                'address' => '桃園市中壢區九和一街48號',
                'telephone' => '03-2805018',
                'remark' => '',
            ],
            96 => 
            [
                'city' => '桃園市',
                'business_name' => '民和大戲院',
                'company_name' => '民和大戲院股份有限公司',
                'national_id_no' => '12982631',
                'total_rooms' => 2,
                'address' => '桃園市八德區廣福路80號3樓',
                'telephone' => '03-3777437',
                'remark' => '',
            ],
            97 => 
            [
                'city' => '桃園市',
                'business_name' => '中源大戲院',
                'company_name' => '中源大戲院',
                'national_id_no' => '43821484',
                'total_rooms' => 3,
                'address' => '桃園市中壢區日新路97號3樓之1',
                'telephone' => '03-4561160',
                'remark' => '',
            ],
            98 => 
            [
                'city' => '桃園市',
                'business_name' => '國賓影城@八德廣豐新天地',
                'company_name' => '國賓影城股份有限公司八德分公司',
                'national_id_no' => '52382486',
                'total_rooms' => 8,
                'address' => '桃園市八德區介壽路一段728號',
                'telephone' => '03-2182898',
                'remark' => '',
            ],
            99 => 
            [
                'city' => '桃園市',
                'business_name' => '桃園統領威秀影城',
                'company_name' => '威秀影城股份有限公司桃園統領分公司',
                'national_id_no' => '51821509',
                'total_rooms' => 20,
                'address' => '桃園市桃園區中正路61號9、10、12樓',
                'telephone' => '03-3333232',
                'remark' => '',
            ],
            100 => 
            [
                'city' => '新竹縣',
                'business_name' => '國際戲院',
                'company_name' => '新竹國際大戲院股份有限公司',
                'national_id_no' => '45044186',
                'total_rooms' => 5,
                'address' => '新竹市文昌街39號2樓',
                'telephone' => '03-5222134',
                'remark' => '',
            ],
            101 => 
            [
                'city' => '新竹縣',
                'business_name' => '國際中興影城',
                'company_name' => '國際中興影城有限公司',
                'national_id_no' => '46387907',
                'total_rooms' => 3,
                'address' => '新竹市林森路32號7、8樓',
                'telephone' => '03-5237077',
                'remark' => '',
            ],
            102 => 
            [
                'city' => '新竹縣',
                'business_name' => '新竹大遠百威秀影城',
                'company_name' => '威秀影城股份有限公司新竹南門分公司',
                'national_id_no' => '80728448',
                'total_rooms' => 11,
                'address' => '新竹市西大路323號8、9、10、11樓',
                'telephone' => '03-5241166',
                'remark' => '',
            ],
            103 => 
            [
                'city' => '新竹縣',
                'business_name' => '新竹巨城威秀影城',
                'company_name' => '威秀影城股份有限公司新竹巨城分公司',
                'national_id_no' => '80279913',
                'total_rooms' => 8,
                'address' => '新竹市民權路176號4樓之3',
                'telephone' => '03-5346999',
                'remark' => '',
            ],
            104 => 
            [
                'city' => '新竹縣',
                'business_name' => '新復珍戲院',
                'company_name' => '新復珍戲院股份有限公司',
                'national_id_no' => '80531780',
                'total_rooms' => 2,
                'address' => '新竹市北門街6號4、5樓',
                'telephone' => '03-5248285',
                'remark' => '',
            ],
            105 => 
            [
                'city' => '苗栗縣',
                'business_name' => '頭份尚順威秀影城',
                'company_name' => '威秀影城股份有限公司苗栗頭份分公司',
                'national_id_no' => '24792875',
                'total_rooms' => 8,
                'address' => '苗栗縣頭份鎮中央路105號7樓',
                'telephone' => '037-686866',
                'remark' => '',
            ],
            106 => 
            [
                'city' => '彰化縣',
                'business_name' => '彰化大戲院',
                'company_name' => '彰化大戲院股份有限公司',
                'national_id_no' => '59290912',
                'total_rooms' => 4,
                'address' => '彰化縣彰化市中正路二段153號3、4樓',
                'telephone' => '04-7255672',
                'remark' => '',
            ],
            107 => 
            [
                'city' => '彰化縣',
                'business_name' => '台灣大戲院',
                'company_name' => '台灣文化企業股份有限公司',
                'national_id_no' => '58651304',
                'total_rooms' => 3,
                'address' => '彰化縣彰化市中正路二段48號',
                'telephone' => '04-7222213',
                'remark' => '',
            ],
            108 => 
            [
                'city' => '彰化縣',
                'business_name' => '員林大戲院',
                'company_name' => '京讚育樂股份有限公司',
                'national_id_no' => '45106149',
                'total_rooms' => 4,
                'address' => '彰化縣員林鎮南昌路39號3樓',
                'telephone' => '04-8351667',
                'remark' => '',
            ],
            109 => 
            [
                'city' => '南投縣',
                'business_name' => '山明電影院',
                'company_name' => '山明電影院',
                'national_id_no' => '78108870',
                'total_rooms' => 2,
                'address' => '南投縣埔里鎮中正路二段389號4樓之2',
                'telephone' => '049-2997878',
                'remark' => '',
            ],
            110 => 
            [
                'city' => '南投縣',
                'business_name' => '南投戲院',
                'company_name' => '南投戲院',
                'national_id_no' => '61215101',
                'total_rooms' => 3,
                'address' => '南投縣南投市大同街87號',
                'telephone' => '049-2242787',
                'remark' => '',
            ],
            111 => 
            [
                'city' => '雲林縣',
                'business_name' => '白宮戲院',
                'company_name' => '白宮戲院',
                'national_id_no' => '64155958',
                'total_rooms' => 4,
                'address' => '雲林縣虎尾鎮中正路257號',
                'telephone' => '05-6322328',
                'remark' => '',
            ],
            112 => 
            [
                'city' => '雲林縣',
                'business_name' => '中華影城',
                'company_name' => '一大育樂股份有限公司',
                'national_id_no' => '16554505',
                'total_rooms' => 8,
                'address' => '雲林縣斗六市雲林路二段19號',
                'telephone' => '05-5354828',
                'remark' => '',
            ],
            113 => 
            [
                'city' => '雲林縣',
                'business_name' => '北港秀泰影城',
                'company_name' => '北港秀泰影城股份有限公司',
                'national_id_no' => '83561013',
                'total_rooms' => 4,
                'address' => '雲林縣北港鎮光復里華南路101號2樓',
                'telephone' => '05-7821895',
                'remark' => '',
            ],
            114 => 
            [
                'city' => '嘉義縣',
                'business_name' => '嘉年華戲院',
                'company_name' => '嘉年華戲院',
                'national_id_no' => '78550228',
                'total_rooms' => 9,
                'address' => '嘉義市中山路617號4樓',
                'telephone' => '05-2250289',
                'remark' => '',
            ],
            115 => 
            [
                'city' => '嘉義縣',
                'business_name' => '嘉義秀泰影城',
                'company_name' => '嘉義秀泰影城股份有限公司',
                'national_id_no' => '42754199',
                'total_rooms' => 11,
                'address' => '嘉義市西區文化路299號6樓',
                'telephone' => '05-2283838',
                'remark' => '',
            ],
            116 => 
            [
                'city' => '屏東縣',
                'business_name' => '中影屏東影城',
                'company_name' => '中影股份有限公司屏東光華分公司',
                'national_id_no' => '28976895',
                'total_rooms' => 8,
                'address' => '屏東縣屏東市民生路248號3、4樓',
                'telephone' => '08-7322043',
                'remark' => '',
            ],
            117 => 
            [
                'city' => '屏東縣',
                'business_name' => '國賓影城@屏東環球購物中心',
                'company_name' => '國賓影城股份有限公司屏東分公司',
                'national_id_no' => '53955905',
                'total_rooms' => 6,
                'address' => '屏東縣屏東市仁愛路90號6、7樓',
                'telephone' => '08-7662128',
                'remark' => '',
            ],
            118 => 
            [
                'city' => '宜蘭縣',
                'business_name' => '友愛影城',
                'company_name' => '友愛影城',
                'national_id_no' => '67902247',
                'total_rooms' => 4,
                'address' => '宜蘭縣宜蘭市舊城東路50號7樓',
                'telephone' => '03-9315666',
                'remark' => '',
            ],
            119 => 
            [
                'city' => '宜蘭縣',
                'business_name' => '日新大戲院',
                'company_name' => '日新大戲院',
                'national_id_no' => '41562807',
                'total_rooms' => 3,
                'address' => '宜蘭縣羅東鎮中山西街17 -1號',
                'telephone' => '03-9542835',
                'remark' => '',
            ],
            120 => 
            [
                'city' => '宜蘭縣',
                'business_name' => '統一戲院',
                'company_name' => '統一戲院',
                'national_id_no' => '42076282',
                'total_rooms' => 1,
                'address' => '宜蘭縣羅東鎮公園路100號3樓',
                'telephone' => '03-9566677',
                'remark' => '',
            ],
            121 => 
            [
                'city' => '宜蘭縣',
                'business_name' => '新月豪華影城',
                'company_name' => '榮江股份有限公司新月影城分公司',
                'national_id_no' => '24562830',
                'total_rooms' => 10,
                'address' => '宜蘭縣宜蘭市民權路二段38巷2號',
                'telephone' => '03-9328833',
                'remark' => '',
            ],
            122 => 
            [
                'city' => '花蓮縣',
                'business_name' => '花蓮秀泰影城',
                'company_name' => '花蓮電影城',
                'national_id_no' => '67946287',
                'total_rooms' => 9,
                'address' => '花蓮縣花蓮市國聯五路69號4、5、6、7樓',
                'telephone' => '03-8337675',
                'remark' => '',
            ],
            123 => 
            [
                'city' => '台東縣',
                'business_name' => '台東秀泰影城',
                'company_name' => '台東娛樂城股份有限公司',
                'national_id_no' => '53558413',
                'total_rooms' => 8,
                'address' => '台東縣台東市新生路93號3樓',
                'telephone' => '089-327755',
                'remark' => '',
            ],
            124 => 
            [
                'city' => '金門縣',
                'business_name' => '金獅影城',
                'company_name' => '台灣創新發展股份有限公司',
                'national_id_no' => '28185226',
                'total_rooms' => 6,
                'address' => '金門縣金湖鎮瓊林里中山路8之6號3、4樓',
                'telephone' => '082-330397',
                'remark' => '',
            ],
            125 => 
            [
                'city' => '金門縣',
                'business_name' => '國賓影城@金門昇恆昌金湖廣場',
                'company_name' => '國賓影城股份有限公司金門分公司',
                'national_id_no' => '24536904',
                'total_rooms' => 6,
                'address' => '金門縣金湖鎮太湖路二段198號6樓',
                'telephone' => '082-330287',
                'remark' => '',
            ],
            126 => 
            [
                'city' => '澎湖縣',
                'business_name' => '澎湖in89豪華影城',
                'company_name' => '豪華大戲院股份有限公司澎湖分公司',
                'national_id_no' => '55664311',
                'total_rooms' => 7,
                'address' => '澎湖縣馬公市同和路158號4樓',
                'telephone' => '06-9276189',
                'remark' => '',
            ],
        ]);
    }
}